/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import socket.GroupChatSocket;

/**
 *
 * @author CongNguyen
 */
public class GroupChatView extends javax.swing.JFrame {

    /**
     * Creates new form GroupChatView
     */
    private int port;
    private String title, address, username;
    private GroupChatSocket groupSocket;
    public GroupChatView(String title, String username) throws IOException {
        this.title = title;
        this.username = username;
        initComponents();
        jLabelGroupName.setText(title);
        switch(title){
            case "Game":
                address = "224.2.2.3";
                port = 8001;
                break;
            case "Xe cộ":
                address = "224.2.2.4";
                port = 8002;
                break;
            case "Kết bạn":
                address = "224.2.2.5";
                port = 8003;
                break;
            default: 
                address = "224.2.2.3";
                port = 8001;
                break;
        }
        groupSocket = new GroupChatSocket(port, address);
        new Thread(){
            @Override
            public void run() {
                while(true){
                    String message = groupSocket.getMessage();
                    jTextAreaScreen.append(message + "\n");
                }
            }          
        }.start();
        this.setLocationRelativeTo(null);
        this.setTitle(username + "-" + title);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGroupName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaScreen = new javax.swing.JTextArea();
        jTextFieldMessageField = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelGroupName.setText("Tên Group");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaScreen.setColumns(20);
        jTextAreaScreen.setRows(5);
        jScrollPane1.setViewportView(jTextAreaScreen);

        jTextFieldMessageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMessageFieldActionPerformed(evt);
            }
        });

        jButtonSend.setText("Gửi");
        jButtonSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSendKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGroupName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelGroupName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendKeyPressed

    private void jTextFieldMessageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMessageFieldActionPerformed
        String message = username + ": " + jTextFieldMessageField.getText().trim();
        jTextFieldMessageField.setText("");        
        groupSocket.sendMessage(message);
    }//GEN-LAST:event_jTextFieldMessageFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelGroupName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaScreen;
    private javax.swing.JTextField jTextFieldMessageField;
    // End of variables declaration//GEN-END:variables
}
