
package User;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.User;
import socket.ClientSocket;

/**
 *
 * @author CongNguyen
 */
public class MenuView extends javax.swing.JFrame {
    private User user;
    private ArrayList<JButton> listselect;
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    /**
     * Creates new form MenuView
     */
    private ClientSocket client;
    private String username;
    private ArrayList<String> friendList;
    private HashMap<String, PersonalChatView> chattingUserList;
    
    public MenuView(String username, ClientSocket client) {
        this.username = username;
        this.client = client;
        this.friendList = client.getListFriend(username);
        this.chattingUserList = new HashMap<>();
        initComponents();
        this.setTitle("Trang chính");        
        this.jLabelUsername.setText(username);      
        this.setLocationRelativeTo(null);
        client.listening(chattingUserList);
        //add listener cho table friendlist
        
        friendListTable.addMouseListener(new MouseAdapter (){
            
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = friendListTable.rowAtPoint(evt.getPoint());
                int col = friendListTable.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {
                    String rcver = (String) friendListTable.getModel().getValueAt(row, col);                    
                    callChatView(username, rcver, client, chattingUserList);
                }
            }
            
        });
        
        groupChatTable.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = groupChatTable.rowAtPoint(evt.getPoint());
                int col = groupChatTable.columnAtPoint(evt.getPoint());
                if(row >= 0 && col >= 0){
                    String rcver = (String) groupChatTable.getModel().getValueAt(row, col);
                    try {
                        GroupChatView view = new GroupChatView(rcver, username);
                        view.setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
        });
        
        //Thiet lap log out khi tat cua so        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                closeConnection();
            }                        
        });

    }
    
    public void callChatView(String sender, String rcver, ClientSocket socket, HashMap<String, PersonalChatView> onlineUser){
        PersonalChatView chatView = new PersonalChatView(sender, rcver, socket, onlineUser);                    
        chattingUserList.put(rcver, chatView);
        chatView.setVisible(true);        
    }
    
    private Object[][] getObjectFriendList(){
        Object[][] obj = new Object[friendList.size()][1];
        for(int i=0; i<friendList.size(); i++){
            obj[i][0] = friendList.get(i);
        }
        return obj;
    }    
    private void closeConnection(){
        if(client != null){
            client.handleLogOut(username);        
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jMenuItem3 = new javax.swing.JMenuItem();
        jTextField1 = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPersonal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendListTable = new javax.swing.JTable();
        jPanelGroup = new javax.swing.JPanel();
        jButtonCreateGroup = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        groupChatTable = new javax.swing.JTable();
        jPanelAddFriends = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearchFriend = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSearchResult = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelUsername.setText("Username");

        friendListTable.setModel(new javax.swing.table.DefaultTableModel(
            getObjectFriendList(),
            new String [] {
                "Người dùng"
            }
        ){
            boolean[] canEdit = new boolean [] {
                false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    jScrollPane1.setViewportView(friendListTable);

    javax.swing.GroupLayout jPanelPersonalLayout = new javax.swing.GroupLayout(jPanelPersonal);
    jPanelPersonal.setLayout(jPanelPersonalLayout);
    jPanelPersonalLayout.setHorizontalGroup(
        jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelPersonalLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(23, Short.MAX_VALUE))
    );
    jPanelPersonalLayout.setVerticalGroup(
        jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelPersonalLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Cá nhân", jPanelPersonal);

    jButtonCreateGroup.setText("Tạo nhóm");
    jButtonCreateGroup.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCreateGroupActionPerformed(evt);
        }
    });

    groupChatTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {"Game"},
            {"Xe cộ"},
            {"Kết bạn"}
        },
        new String [] {
            "Nhóm chat"
        }
    ){
        boolean[] canEdit = new boolean [] {
            false
        };
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane4.setViewportView(groupChatTable);

    javax.swing.GroupLayout jPanelGroupLayout = new javax.swing.GroupLayout(jPanelGroup);
    jPanelGroup.setLayout(jPanelGroupLayout);
    jPanelGroupLayout.setHorizontalGroup(
        jPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelGroupLayout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jButtonCreateGroup)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
    );
    jPanelGroupLayout.setVerticalGroup(
        jPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelGroupLayout.createSequentialGroup()
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(707, 707, 707)
            .addComponent(jButtonCreateGroup)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Nhóm", jPanelGroup);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Tìm kiếm:");

    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jTableSearchResult.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Kết quả tìm kiếm"
        }
    ));
    jTableSearchResult.setRowHeight(60);
    jScrollPane3.setViewportView(jTableSearchResult);

    javax.swing.GroupLayout jPanelAddFriendsLayout = new javax.swing.GroupLayout(jPanelAddFriends);
    jPanelAddFriends.setLayout(jPanelAddFriendsLayout);
    jPanelAddFriendsLayout.setHorizontalGroup(
        jPanelAddFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelAddFriendsLayout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextFieldSearchFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1)
            .addContainerGap(154, Short.MAX_VALUE))
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    );
    jPanelAddFriendsLayout.setVerticalGroup(
        jPanelAddFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelAddFriendsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanelAddFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelAddFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSearchFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Kết bạn", jPanelAddFriends);

    jLabel2.setText("Xin chào:");

    jMenu1.setText("Lựa chọn");
    jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenu1MouseClicked(evt);
        }
    });

    jMenuItemLogout.setText("Đăng xuất");
    jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemLogoutActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemLogout);

    jMenuItemExit.setText("Thoát");
    jMenuItemExit.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jMenuItemExitMouseClicked(evt);
        }
    });
    jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemExitActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemExit);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelUsername)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(59, 59, 59)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    
    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất á?","Xác nhận thoát",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(choice == JOptionPane.YES_OPTION){
            client.handleLogOut(username);
            this.dispose();
            LoginView lv = new LoginView();
            lv.setVisible(true);
            
        }
        else if(choice==JOptionPane.NO_OPTION){
            closeConnection();
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
       
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExitMouseClicked

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát a?","Xác nhận thoát",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(choice == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else if(choice==JOptionPane.NO_OPTION){
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
       
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCreateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateGroupActionPerformed
        // TODO add your handling code here:
        CreateGroup cg = new CreateGroup();
        cg.setVisible(true);

    }//GEN-LAST:event_jButtonCreateGroupActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable friendListTable;
    private javax.swing.JTable groupChatTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCreateGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JPanel jPanelAddFriends;
    private javax.swing.JPanel jPanelGroup;
    private javax.swing.JPanel jPanelPersonal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableSearchResult;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldSearchFriend;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
